apiVersion: v1
kind: ReplicationController
metadata:
  name: kploy-registry-rc
spec:
  replicas: 1
  selector:
    app: kploy-registry
  template:
    metadata:
      labels:
        app: kploy-registry
    spec:
      containers:
      - image: mhausenblas/kploy.net
        imagePullPolicy: Always
        name: kar
        ports:
          - containerPort: 9876